CREATE TABLE `data_platform_equipment_master_general_data`
(
    `Equipment`                          int(20) NOT NULL,
    `BusinessPartner`                    int(12) DEFAULT NULL,
    `ValidityStartDate`                  date DEFAULT NULL,
    `ValidityEndDate`                    date DEFAULT NULL,
    `EquipmentName`                      varchar(40) DEFAULT NULL,
    `EquipmentType`                      varchar(10) DEFAULT NULL,
    `EquipmentCategory`                  varchar(1) DEFAULT NULL,
    `TechnicalObjectType`                varchar(10) DEFAULT NULL,
    `GrossWeight`                        float(15) DEFAULT NULL,
    `NetWeight`                          float(15) DEFAULT NULL,
    `WeightUnit`                         varchar(3) DEFAULT NULL,
    `SizeOrDimensionText`                varchar(18) DEFAULT NULL,
    `InventoryNumber`                    varchar(25) DEFAULT NULL,
    `OperationStartDate`                 date DEFAULT NULL,
    `OperationStartTime`                 time DEFAULT NULL,
    `OperationEndDate`                   date DEFAULT NULL,
    `OperationEndTime`                   time DEFAULT NULL,
    `EquipmentStandardID`                varchar(18) DEFAULT NULL,
    `EquipmentIndustryStandardName`      varchar(200) DEFAULT NULL,
    `CountryOfOrigin`                    varchar(3) DEFAULT NULL,
    `CountryOfOriginLanguage`            varchar(2) DEFAULT NULL,
    `BarcodeType`                        varchar(20) DEFAULT NULL,
    `AcquisitionDate`                    date DEFAULT NULL,
    `Manufacturer`                       int(12) DEFAULT NULL,
    `ManufacturedCountry`                varchar(3) DEFAULT NULL,
    `ConstructionYear`                   int(4) DEFAULT NULL,
    `ConstructionMonth`                  int(2) DEFAULT NULL,
    `ManufacturerPartNmbr`               varchar(100) DEFAULT NULL,
    `ManufacturerSerialNumber`           varchar(100) DEFAULT NULL,
    `MaintenancePlantBusinessPartner`    int(12) NOT NULL,
    `MaintenancePlant`                   varchar(4) NOT NULL,
    `AssetLocation`                      varchar(100) DEFAULT NULL,
    `AssetRoom`                          varchar(100) DEFAULT NULL,
    `PlantSection`                       varchar(100) DEFAULT NULL,
    `WorkCenter`                         varchar(8) DEFAULT NULL,
    `Project`                            varchar(24) DEFAULT NULL,
    `MaintenancePlannerGroup`            varchar(3) DEFAULT NULL,
    `CatalogProfile`                     varchar(9) DEFAULT NULL,
    `FunctionalLocation`                 varchar(30) DEFAULT NULL,
    `SuperordinateEquipment`             varchar(18) DEFAULT NULL,
    `EquipInstallationPositionNmbr`      varchar(4) DEFAULT NULL,
    `EquipmentIsAvailable`               tinyint(1) DEFAULT NULL,
    `EquipmentIsInstalled`               tinyint(1) DEFAULT NULL,
    `EquipIsAllocToSuperiorEquip`        tinyint(1) DEFAULT NULL,
    `EquipHasSubOrdinateEquipment`       varchar(1) DEFAULT NULL,
    `MasterFixedAsset`                   varchar(10) DEFAULT NULL,
    `FixedAsset`                         varchar(4) DEFAULT NULL,
    `CreationDate`                       date DEFAULT NULL,
    `LastChangeDateTime`                 time DEFAULT NULL,
    `IsMarkedForDeletion`                tinyint(1) DEFAULT NULL,

    PRIMARY KEY (`Equipment`),
    
    CONSTRAINT `DPFMEquipmentMasterGeneralDataBusinessPartner_fk` FOREIGN KEY (`BusinessPartner`) REFERENCES `data_platform_business_partner_genaral_data` (`BusinessPartner`),
    CONSTRAINT `DPFMEquipmentMasterGeneralDataEquipmentType_fk` FOREIGN KEY (`EquipmentType`) REFERENCES `data_platform_equipment_type_equipment_type_data` (`EquipmentType`),
    CONSTRAINT `DPFMEquipmentMasterGeneralDataWeightUnit_fk` FOREIGN KEY (`WeightUnit`) REFERENCES `data_platform_quantity_unit_quantity_unit_data` (`QuantityUnit`),
    CONSTRAINT `DPFMEquipmentMasterGeneralDataCountryOfOrigin_fk` FOREIGN KEY (`CountryOfOrigin`) REFERENCES `data_platform_country_country_data` (`Country`),
    CONSTRAINT `DPFMEquipmentMasterGeneralDataCountryOfOriginLanguage_fk` FOREIGN KEY (`CountryOfOriginLanguage`) REFERENCES `data_platform_language_language_data` (`Language`),
    CONSTRAINT `DPFMEquipmentMasterGeneralDataManufacturer_fk` FOREIGN KEY (`Manufacturer`) REFERENCES `data_platform_business_partner_genaral_data` (`BusinessPartner`),
    CONSTRAINT `DPFMEquipmentMasterGeneralDataManufacturedCountry_fk` FOREIGN KEY (`ManufacturedCountry`) REFERENCES `data_platform_country_country_data` (`Country`),
    CONSTRAINT `DPFMEquipmentMasterGeneralDataMaintenancePlant_fk` FOREIGN KEY (`MaintenancePlantBusinessPartner`, `MaintenancePlant`) REFERENCES `data_platform_plant_genaral_data` (`BusinessPartner`, `Plant`),
    CONSTRAINT `DPFMEquipmentMasterGeneralDataWorkCenter_fk` FOREIGN KEY (`WorkCenter`) REFERENCES `data_platform_work_center_genaral_data` (`WorkCenter`),
    CONSTRAINT `DPFMEquipmentMasterGeneralDataProject_fk` FOREIGN KEY (`Project`) REFERENCES `data_platform_project_project_data` (`Project`)

) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
